version: "3.9"
services:

  app:
      build:
        args:
          - USER=admin
          - NEW_UID=${NEW_UID}
          - NEW_GID=${NEW_GID}
          - TIMEZONE=${TIMEZONE}
        context: ./
        dockerfile: Dockerfile
      image: ${APP_NAME}
      container_name: ${APP_NAME}-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - laravel

  db:
      image: mariadb
      container_name: ${APP_NAME}-mariadb
      restart: unless-stopped
      ports:
        - 3306:3306
      environment:
        MARIADB_DATABASE: ${DB_DATABASE}
        MARIADB_PASSWORD: ${DB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        MARIADB_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mariadb
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
      networks:
        - laravel

  nginx:
      image: nginx
      container_name: ${APP_NAME}-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
        - laravel

networks:
  laravel:
    driver: bridge
